<?php

declare(strict_types=1);

return [
    'relationId' => 62428,

    'languages' => ['de', 'en'],

    'exclude' => [
        'relation' => [],
        'way' => [],
    ],

    'gender' => [
        'relation' => [
            '4271290' => 'M' // Agricolaplatz: eine der 42 Münchner Geiseln König Gustavs II. Adolf
        ],
        'way' => [
            '4271290' => 'M', // Agricolaplatz: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4218701' => 'M', // Agricolastraße: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4271289' => 'M', // Agricolastraße: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '69688189' => 'M', // Agricolastraße: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '152273429' => 'M', // Agricolastraße: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '172200030' => 'M', // Agricolastraße: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '426277800' => 'M', // Agricolastraße: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '426277801' => 'M', // Agricolastraße: Agricola, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4585970' => 'M', // Aindorferstraße: Aindorfer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4585971' => 'M', // Aindorferstraße: Aindorfer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5079717' => 'M', // Aindorferstraße: Aindorfer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5081024' => 'M', // Aindorferstraße: Aindorfer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '63094057' => 'M', // Aindorferstraße: Aindorfer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '159179304' => 'M', // Aindorferstraße: Aindorfer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4218695' => 'M', // Alblstraße: Albl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '35095323' => '-', // Alpenveilchenstraße: Blumenart Alpenveilchen
            '4515580' => '-', // Altmannstraße: Adelsgeschlecht
            '158803933' => '-', // Altmannstraße: Adelsgeschlecht
            '4519701' => '-', // Altmannstraße: Adelsgeschlecht
            '4218708' => '-', // Am Laimer Anger
            '4497104' => '-', // Barmer Straße: Wuppertaler Stadtbezirk
            '16943294' => 'M', // Baudererstraße: Heinrich Bauderer, Volkssänger
            '4585935' => 'M', // Berchemstraße: Anton Freiherr von Berchem, kurfürstlicher Rat unter Max Emanuel
            '4885797' => 'M', // Berchemstraße: Anton Freiherr von Berchem, kurfürstlicher Rat unter Max Emanuel
            '16943298' => 'M', // Byecherstraße: Byecher, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4515588' => 'M', // Camerloherstraße: Camerloher, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5081108' => 'M', // Camerloherstraße: Camerloher, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '8351859' => 'M', // Camerloherstraße: Camerloher, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '16943255' => '-', // Dichtlstraße: Dichtl, ein Münchner Patriziergeschlecht
            '25777548' => 'M', // Egetterstraße: Egetter, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4537283' => 'M', // Endelhauserstraße: Johann Endelhauser, Münchner Stadtrichter im 15. Jahrhundert
            '81976798' => 'M', // Endelhauserstraße: Johann Endelhauser, Münchner Stadtrichter im 15. Jahrhundert
            '81976800' => 'M', // Endelhauserstraße: Johann Endelhauser, Münchner Stadtrichter im 15. Jahrhundert
            '16943145' => 'M', // Eringerstraße: nach dem Volksschauspieler Josef Georg Eringer
            '67379640' => 'M', // Eringerstraße: nach dem Volksschauspieler Josef Georg Eringer
            '5079689' => '-', // Flantinstraße: nach dem Münchner Ratsherrengeschlecht der Flantins
            '5085894' => '-', // Fleckhammerstraße: nach der Münchner Ratsherrenfamilie Fleckhammer
            '5079870' => '-', // Gaishoferstraße: nach dem Münchner Ratsherrengeschlecht Gaishofer
            '4218694' => '-', // Genovevaweg: zwei unterschiedliche Möglichkeiten, Genoveva Winkler oder Volksstück Genovevaspiel
            '16943300' => 'M', // Geßlerstraße: Geßler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '16943302' => 'M', // Geigerstraße: Tobias Geiger, wurde 1601 Münchner Stadtarzt, Oberfeldarzt der bayerischen Armee
            '4218700' => 'M', // Geyerspergerstraße: Geyersperger, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4585941'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '272455482'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '220851263'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4886833'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4497089'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '30578368'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '153184477'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '38077003'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '69688181'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '594740424'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '686292119'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '343008978'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '220851264'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '272455485'  => 'M', // Gotthardstraße: Joachim Gotthard, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5079653' => 'M', // Guido-Schnebele-Straße: Guido Schneble (1887 — 1959), Mitglied und Vorsitzender des Bezirksausschusses Laim
            '5081050' => 'M', // Guido-Schnebele-Straße: Guido Schneble (1887 — 1959), Mitglied und Vorsitzender des Bezirksausschusses Laim
            '63954836' => 'M', // Guido-Schnebele-Straße: Guido Schneble (1887 — 1959), Mitglied und Vorsitzender des Bezirksausschusses Laim
            '435817314' => 'M', // Guido-Schnebele-Straße: Guido Schneble (1887 — 1959), Mitglied und Vorsitzender des Bezirksausschusses Laim
            '416322074' => 'M', // Gunzenlehstraße: nach Gunzenleh, einer ehemaligen Burg der Welfen bei Mering
            '16943249' => 'M', // Hartelstraße: nach dem Schlossherrn Hartel von Pasing
            '16799626' => 'M', // Helmpertstraße: nach dem Edlen Helmpert, der in einer Urkunde erwähnt wird, in der auch Laim zum ersten Mal nachweislich genannt ist.
            '16799764' => 'M', // Helmpertstraße: nach dem Edlen Helmpert, der in einer Urkunde erwähnt wird, in der auch Laim zum ersten Mal nachweislich genannt ist.
            '386701461' => 'M', // Helmpertstraße: nach dem Edlen Helmpert, der in einer Urkunde erwähnt wird, in der auch Laim zum ersten Mal nachweislich genannt ist.
            '4586040' => 'M', // Horwerkstraße: Maler der Spätgotik Niclas Horwerk
            '4586008' => 'M', // Hörkherstraße: Hörkher, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5079661' => 'M', // Inderstorferstraße: Inderstorfer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '16943267' => 'M', // Isbertstraße: nach dem Edlen Isbert, der vermutlich das erste Pasinger Schloss erbaute
            '178651083' => 'F', // Käthe-Bauer-Weg: Käthe Bauer, Ehrenmitglied der Arbeiterwohlfahrt
            '851117646' => 'F', // Käthe-Bauer-Weg: Käthe Bauer, Ehrenmitglied der Arbeiterwohlfahrt
            '4586063' => 'M', // Kirchmairstraße: Kirchmair, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '237418954' => 'M', // Kirchmairstraße: Kirchmair, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '17247873' => 'M', // Lanzstraße: Lanz, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4218712' => 'M', // Mathunistraße: nach dem bischöflichen Beauftragten Mathuni
            '4218713' => 'M', // Mathunistraße: nach dem bischöflichen Beauftragten Mathuni
            '16798350' => 'M', // Perhamerstraße: Perhamer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '118682364' => 'M', // Perhamerstraße: Perhamer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '118682365' => 'M', // Perhamerstraße: Perhamer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '426277802' => 'M', // Perhamerstraße: Perhamer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '706391878' => 'M', // Perhamerstraße: Perhamer, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '30803854' => 'M', // Pfarrer-Endres-Weg: Pfarrer Otto Endres (* 15.01.1897 in München, † 17.09.1971 ebenda).
            '4271294' => 'M', // Pronnerplatz: Pronner, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '159179344' => 'M', // Rapotostraße: nach Rapoto, einem Münchner Adeligen
            '4271286' => 'M', // Rappstraße: Rapp, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '16943297' => 'M', // Rechpacherstraße: Rechpacher, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5079664' => 'M', // Reindlstraße: nach dem ehemaligen Bürgermeister Benno Ferdinand von Reindl
            '5085887' => 'M', // Reindlstraße: nach dem ehemaligen Bürgermeister Benno Ferdinand von Reindl
            '4271292' => 'M', // Ronpeckhstraße: Ronpeckh, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '16943312' => 'M', // Rushaimerstraße: altes Münchner Patriziergeschlecht
            '5079677' => 'M', // Saherrstraße: Saherr, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5079852' => 'M', // Saherrstraße: Saherr, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5085885' => 'M', // Saherrstraße: Saherr, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '24952474' => 'M', // Saherrstraße: Saherr, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '16800467' => 'M', // Schifferlstraße: Schifferl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '159179348' => 'M', // Schrottstraße: benannt nach dem Magistratsrat Ludwig Schrott
            '4515608' => 'M', // Siglstraße: Sigl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '8147776' => 'M', // Siglstraße: Sigl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '56542061' => 'M', // Siglstraße: Sigl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '97857349' => 'M', // Siglstraße: Sigl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '373410845' => 'M', // Siglstraße: Sigl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '452205999' => 'M', // Siglstraße: Sigl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4218703' => 'M', // Stöberlstraße: Stöberl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '81081318' => 'M', // Stöberlstraße: Stöberl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '152113295' => 'M', // Stöberlstraße: Stöberl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '152113297' => 'M', // Stöberlstraße: Stöberl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '159179366' => 'M', // Stöberlstraße: Stöberl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4218723' => 'M', // Stroblstraße: Strobl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '8351861' => 'M', // Stroblstraße: Strobl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '243126331' => 'M', // Stroblstraße: Strobl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '424714808' => 'M', // Stroblstraße: Strobl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '424714809' => 'M', // Stroblstraße: Strobl, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '5080877' => 'M', // Sturmstraße: Albin Sturm, Lehrer
            '4218698' => 'M', // Reutterstraße: Reutter, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4271284' => 'M', // Reutterstraße: Reutter, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '16943253' => 'M', // Reutterstraße: Reutter, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '159179345' => 'M', // Reutterstraße: Reutter, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '159179346' => 'M', // Reutterstraße: Reutter, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4271288' => 'M', // Stögerstraße: nach dem Buchhändler und Hofbibliothekar Josef Stöger
            '5080869' => 'M', // Thurneyssenstraße: Johann Jakob Thurneyssen, Kupferstecher
            '209587270' => 'M', // Thurneyssenstraße: Johann Jakob Thurneyssen, Kupferstecher
            '4218705' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4218715' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4218716' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4515611' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '152280712' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '152280713' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '237418956' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '237421404' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '262201842' => 'M', // Valpichlerstraße: Valpichler, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '4586071' => 'M', // Weichselbaumerstraße: Schulkommissar Matthias Weichselbaumer
            '4218688' => 'M', // Wilhelm-Mayr-Straße: Wilhelm Mayr, eine der 42 Münchner Geiseln König Gustavs II. Adolf
            '17249132' => 'M', // Widarkisstraße: Widarkis oder Widarsik, einer der frühen Einwohner von Pasing.
            '312037058' => 'F', // Schulmeierweg: nach Therese Schulmeier, die eine Stiftung für behinderte Kinder errichtete
            '5085824' => '-', // Gunzenlehstraße: nach Gunzenleh, einer ehemaligen Burg der Welfen bei Mering
            '5085831' => '-', // Gunzenlehstraße: nach Gunzenleh, einer ehemaligen Burg der Welfen bei Mering
            '189696135' => '-', // Gunzenlehstraße: nach Gunzenleh, einer ehemaligen Burg der Welfen bei Mering
            '261352051' => '-', // Gunzenlehstraße: nach Gunzenleh, einer ehemaligen Burg der Welfen bei Mering
            '261352052' => '-', // Gunzenlehstraße: nach Gunzenleh, einer ehemaligen Burg der Welfen bei Mering
            '5079666' => '-', // Högerstraße: Münchner Bürgerfamilie Höger
            '5080996' => '-', // Käpflstraße: nach der Münchner Kaufmannsfamilie Käpfl.
            '420012960' => '-', // Käpflstraße: nach der Münchner Kaufmannsfamilie Käpfl.
            '16798351' => '-', // Neuburgerstraße: nach der Pasinger Familie Neuburger
            '172593388' => '-', // Perkhoferstraße: nach der Münchner Patrizierfamilie Perkhofer.
            '4515585' => '-', // Rattenhuberstraße: nach einer alten Münchner Bürgerfamile.
            '30673310' => '-', // Schlangenwegerl: nach den hier früher häufig vorkommenden Schlangen.
            '4885823' => '-', // Stegener Weg: Stegan, ein Ortsteil von der Gemeinde Inning am Ammersee.
            '159179354' => '-', // Seehoferstraße: nach der Münchner Bürgerfamilie Seehofer.
            '178966547' => '-', // Stegener Weg: nach einem Ortsteil von der Gemeinde Inning am Ammersee.
            '293561755' => '-', // Stegener Weg: nach einem Ortsteil von der Gemeinde Inning am Ammersee.
            '16943296' => 'M', // Sulzbeckstraße: Josef Sulzbeck, Volkssänger und Münchner Original
            '4218691' => '-', // Zündterstraße: nach dem Beginn der Straße am Grenzstein (Zintstei) von Pasing.
            '35134707' => '-', // Riegerhofstraße: nach einem alten Laimer Hofnamen
            '422789263' => '-', // Riegerhofstraße: nach einem alten Laimer Hofnamen
            '422789264' => '-', // Riegerhofstraße: nach einem alten Laimer Hofnamen
            '4218710' => '-', // Riegerhofweg: nach einem alten Laimer Hofnamen
            '4515584' => '-', // Weißenfelderstraße: Münchner Patrizierfamilie
            '4885794' => '-', // Weißenfelderplatz: Münchner Patrizierfamilie
            '4009458' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '4043488' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '8058985' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '51734648' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '62334750' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '71360465' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '81976285' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '172485422' => '-', // Elsenheimerstraße: Familie Elsenheimer, aus der mehrere Mitglieder wichtige Funktionen in der Stadt München innehatten
            '4515579' => '-', // Fachnerstraße: nach den Fachners, einem Münchner Ratsherrengeschlecht,
            '4515583' => '-', // Fachnerstraße: nach den Fachners, einem Münchner Ratsherrengeschlecht,
            '4885791' => '-', // Fachnerstraße: nach den Fachners, einem Münchner Ratsherrengeschlecht,
            '4885792' => '-', // Fachnerstraße: nach den Fachners, einem Münchner Ratsherrengeschlecht,
            '154945137' => '-', // Fachnerstraße: nach den Fachners, einem Münchner Ratsherrengeschlecht,
            '4043486' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '51734647' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '55795330' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '61738278' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '152062771' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '316110464' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '426957011' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '438950423' => '-', // Friedenheimer Brücke: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand,
            '4079075' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '56542039' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '56197311' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '152276372' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '152276374' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '152277273' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '241720920' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '366209677' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '497390606' => '-', // Friedenheimer Straße: nach dem ehemaligen Gutshof Friedenheim, der sich dort befand.
            '4404142' => 'M', // Bertholdstraße: Berthold, Pfarrer aus Eching, 12. Jahrhundert
            '4406249' => 'M', // Dolleschelstraße: Hubert Dolleschel, SPD-Mitglied und Mitbegründer der Arbeiterwohlfahrt, 1876-1938
            '5033219' => 'M', // Ostermayrstraße: Ludwig Ostermayr, Ökonom, vergrößerte im 17. Jhdt . die dem Kloster Schäftlarn gehörende Schwaige in Milbertshofen
            '23281710' => 'M', // Zanderstraße: Geheimrat Zander, ehem. Inhaber der Möbelfabrik Milbertshofen
            '31662607' => 'M', // Probst-Heinrich-Straße: Probst Heinrich von Schäftlarn, schlichtete im 12. Jhdt. den zwischen dem Kloster Schäftlarn und dem Domstift Freising
            '23820564' => 'F', // Rose-Pichler-Weg: Rose Pichler, Gründerin der Rose und Alphonse Pichler-Stiftung
            '145737490' => 'F', // Rose-Pichler-Weg: Rose Pichler, Gründerin der Rose und Alphonse Pichler-Stiftung
            '145737491' => 'F', // Rose-Pichler-Weg: Rose Pichler, Gründerin der Rose und Alphonse Pichler-Stiftung
            '8005581' => 'F', // Rose-Pichler-Weg: Rose Pichler, Gründerin der Rose und Alphonse Pichler-Stiftung
            '339700502' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700503' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700504' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700505' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700506' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700507' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700508' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700509' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700510' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700511' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700512' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700513' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700514' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '23034604' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '23281718' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '28303830' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '339700515' => 'M', // Hanselmannstraße: Leonhard Hanselmannn, ehemaliger Bürgermeister von Milbertshofen
            '4406767' => 'M', // Anton-Ditt-Bogen: Anton Ditt, Initiator des Euro-Industrieparkes 
            '4537087' => 'M', // Anton-Ditt-Bogen: Anton Ditt, Initiator des Euro-Industrieparkes 
            '424185790' => 'M', // Anton-Ditt-Bogen: Anton Ditt, Initiator des Euro-Industrieparkes 
            '17940592' => 'M', // El-Thouni-Weg: Khadr El Thouni, ägyptischer Gewichtheber. 
            '929558732' => 'M', // El-Thouni-Weg: Khadr El Thouni, ägyptischer Gewichtheber. 
            '376839301' => 'M', // Schollerweg: Otto Scholler, ehemaliger Leiter der Verkehrsbetriebe München
            '376839304' => 'M', // Schollerweg: Otto Scholler, ehemaliger Leiter der Verkehrsbetriebe München
            '996920455' => 'M', // Schollerweg: Otto Scholler, ehemaliger Leiter der Verkehrsbetriebe München
            '23374526' => 'M', // Schollerweg: Otto Scholler, ehemaliger Leiter der Verkehrsbetriebe München
            '116786306' => 'M', // Schollerweg: Otto Scholler, ehemaliger Leiter der Verkehrsbetriebe München
            '361229793' => 'M', // Schollerweg: Otto Scholler, ehemaliger Leiter der Verkehrsbetriebe München
            '23605481' => 'M', // Schollerweg: Otto Scholler, ehemaliger Leiter der Verkehrsbetriebe München
            '29418700' => 'M', // Ansprengerstraße: Ansprenger Alois, K. Kommerzienrat, Baumeister, buergerlicher Magistrat und Landrat 
            '123106263' => 'M', // Ansprengerstraße: Ansprenger Alois, K. Kommerzienrat, Baumeister, buergerlicher Magistrat und Landrat 
            '4519924' => '-', // Ansbacher Straße: Ansbach, Stadt Ansbach 
            '78713657' => '-', // Arcisstraße: Arcisschlacht, eine Schlacht waehrend der Befreiungskriege 
            '151996168' => '-', // Arcisstraße: Arcisschlacht, eine Schlacht waehrend der Befreiungskriege 
            '4005344' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '25591841' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '26241111' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '26416346' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '27807199' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '28428153' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '30816876' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '30816921' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '30816922' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '36580436' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '44979189' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '44979190' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '47634448' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '47634455' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '49602856' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '49602857' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '49917019' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '56122343' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '56122344' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '56122345' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '56122346' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '59479808' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '59479810' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '71143057' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '88722466' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '124842492' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '124842493' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '124842494' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '124842495' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '129552585' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '136057338' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '159924390' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '265416839' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '265416843' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '267059261' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '267059262' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '292612489' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '338649272' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '376107897' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '449594859' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '449595750' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '449601150' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '476398408' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '494904648' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '494904649' => '-', // Belgradstraße: Belgrad, Die Schlacht von Belgrad 1717 
            '6055627' => '-', // Birnauer Straße: Birnau, Wallfahrtskirche Birnau 
            '81958060' => '-', // Birnauer Straße: Birnau, Wallfahrtskirche Birnau 
            '89360845' => '-', // Birnauer Straße: Birnau, Wallfahrtskirche Birnau 
            '311413661' => '-', // Birnauer Straße: Birnau, Wallfahrtskirche Birnau 
            '311415321' => '-', // Birnauer Straße: Birnau, Wallfahrtskirche Birnau 
            '5219113' => 'M', // Bummstraße: Bumm, Deutscher Psychiater 
            '19680434' => '-', // Burgunderstraße: Burgunder, Volksgruppe 
            '157032551' => 'F', // Centa-Herker-Bogen: Centa Herker, politisch aktive Frau und Zeitzeugin 
            '157090547' => 'M', // Egmontstraße: Egmond, Staatsmann 
            '749798608' => 'M', // Fritz-Schuster-Straße: Fritz Schuster, SPD-Stadtratsmitglied 
            '157090551' => 'M', // Fürstenbergstraße: Landgraf Egon von Fuerstenberg, kaempfte gegen die Schweden 
            '157090556' => '-', // Gartenstraße: Garten, Hier befanden sich zahlreiche Gaerten 
            '4519923' => 'M', // Gentzstraße: Gentz, Gemeindebevollmaechtigter 
            '851113019' => '-', // Georgenstraße: Georgenschwaige, Nach dem Hofgut Georgenschwaige 
            '851113021' => '-', // Georgenstraße: Georgenschwaige, Nach dem Hofgut Georgenschwaige 
            '851113023' => '-', // Georgenstraße: Georgenschwaige, Nach dem Hofgut Georgenschwaige 
            '851113024' => '-', // Georgenstraße: Georgenschwaige, Nach dem Hofgut Georgenschwaige 
            '851113025' => '-', // Georgenstraße: Georgenschwaige, Nach dem Hofgut Georgenschwaige 
            '19680463' => 'M', // Gernotstraße: Gernot, Figur aus den Nibelungenliedern 
            '157038597' => 'M', // Gernotstraße: Gernot, Figur aus den Nibelungenliedern 
            '157038599' => 'M', // Gernotstraße: Gernot, Figur aus den Nibelungenliedern 
            '19680495' => 'M', // Giselherstraße: Giselher, Figur aus den Nibelungenliedern 
            '4520027' => '-', // Infanteriestraße: Infanterie, Hier stand eine Kaserne 
            '22718061' => '-', // Infanteriestraße: Infanterie, Hier stand eine Kaserne 
            '87964579' => '-', // Infanteriestraße: Infanterie, Hier stand eine Kaserne 
            '157028288' => '-', // Infanteriestraße: Infanterie, Hier stand eine Kaserne 
            '161765725' => '-', // Infanteriestraße: Infanterie, Hier stand eine Kaserne 
            '8042147' => 'F', // Isoldenstraße: Isolde, Figur aus Tristan und Isolde 
            '50232915' => 'F', // Isoldenstraße: Isolde, Figur aus Tristan und Isolde 
            '146789787' => 'F', // Isoldenstraße: Isolde, Figur aus Tristan und Isolde 
            '53267456' => '-', // Kaiserplatz: Kaiser, Erinnerung an die Proklamierung des deutschen Kaiserreichs 
            '80819309' => '-', // Kaiserstraße: Kaiser, Erinnerung an die Proklamierung des deutschen Kaiserreichs 
            '83028196' => '-', // Kaiserstraße: Kaiser, Erinnerung an die Proklamierung des deutschen Kaiserreichs 
            '300559210' => '-', // Kaiserstraße: Kaiser, Erinnerung an die Proklamierung des deutschen Kaiserreichs 
            '153625894' => 'M', // König-Marke-Straße: König Marke, Gestalt aus Tristan und Isolde 
            '4056046' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '4698755' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '5403376' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '31343389' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '31351672' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '36771938' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '50232911' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '147950387' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '151786524' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '171280981' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '269716429' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '269716437' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '1023916092' => '-', // Lerchenauer Straße: Lerchenau, Straße zum Lerchenauer See 
            '7390839' => '-', // Montsalvatstraße: Montsalvat, Sagenhafte Burg 
            '34160676' => '-', // Nordendstraße: Nordende, Topologische Lage 
            '89699184' => '-', // Nordendstraße: Nordende, Topologische Lage 
            '93072396' => '-', // Nordendstraße: Nordende, Topologische Lage 
            '155586944' => '-', // Nordendstraße: Nordende, Topologische Lage 
            '392219837' => '-', // Nordendstraße: Nordende, Topologische Lage 
            '392219838' => '-', // Nordendstraße: Nordende, Topologische Lage 
            '5343456' => 'M', // Pündterplatz: Pündter, Vorstand des Bezirksamts Muenchen 
            '157107344' => 'M', // Pündterplatz: Pündter, Vorstand des Bezirksamts Muenchen 
            '157067000' => 'M', // Sailerstraße: Sailer, Schatzmeister des Kurfuersten 
            '157090559' => 'M', // Sailerstraße: Sailer, Schatzmeister des Kurfuersten 
            '23540976' => '-', // Sankt-Blasien-Straße: Sankt Blasien, Kloster 
            '4585573' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '13879585' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '30616063' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '31344435' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '31352158' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '32795431' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '32795432' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '36771940' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '36965393' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '37666059' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '38868057' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '38868058' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '39378779' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '39378780' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '42446216' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '42446217' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '42484131' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '47634457' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '51086842' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '51095967' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '51095970' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '51156715' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '51156718' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '53040272' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '58765884' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '58765885' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '58765886' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '58765887' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '59479811' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '88535432' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '160026050' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '167440186' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '267576364' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '287522841' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '307219406' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '311337460' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '311337461' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '335244088' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '349195366' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '349195369' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '353017401' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '353017402' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '371752183' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '371861004' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '371861005' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '371861008' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '384532213' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '549023362' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '552799309' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '552799310' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '552799312' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '552799313' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '552799315' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '845930949' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '845930952' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '851113020' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '851139057' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '874500364' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '874500366' => '-', // Schleißheimer Straße: Schleissheim, Strasse fuehrt zur Gemeinde 
            '4673715' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '27822841' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '41053396' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '53533143' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '87602698' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '87602699' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '95735556' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '107594672' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '142786395' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '151866165' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '151866167' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '157032565' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '209315490' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '287514639' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '310823109' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '310823110' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '310823112' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '310823113' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '316538694' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '371866615' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '371866616' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '371866617' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '394489297' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '409064419' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '409064420' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '409064421' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '409064422' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '409064423' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '421746940' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '421746944' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '424062931' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '456158814' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '475109924' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '475919639' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '475919640' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '475919641' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '475919642' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '475919643' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '475919644' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '1023662070' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '1023662071' => '-', // Schwere-Reiter-Straße: Schwere Reiter, Zur Erinnerung an Kavallerie Regiment 
            '450252890' => '-', // Stadtplatz: Stadt, Phantasielose Platznamenfindung 
            '26241116' => 'M', // Voelderndorffstraße: Voelderndorff, Schriftsteller 
            '88718514' => 'M', // Voelderndorffstraße: Voelderndorff, Schriftsteller 
            '157090568' => 'M', // Wertherstraße: Werther, Romanfigur 
            '157090569' => 'M', // Wilhelm-Meister-Straße: Wilhelm Meister, Aus dem Roman 
        ],
    ],

    'instances' => [
        'Q5'        => true,  // human
        'Q2985549'  => true,  // mononymous person
        'Q20643955' => true,  // human biblical figure

        'Q8436'     => false, // family
        'Q101352'   => false, // family name
        'Q327245'   => false, // team
        'Q3046146'  => false, // married couple
        'Q13417114' => false, // noble family
    ],
];
